### ISSUE TITLE
"Invert Action" doesn't seem to work correctly?

### ISSUE THREAD

**Issue by TonyAki** [valinet/ThinkPadLEDControl#3]
Hi,
Thanks for making this, it's really cool!
My desired use of this utility is to have the microphone mute LED permanently inverted. That is, when the mic is muted, LED is off, and when the mic is active, LED turns on. This is the opposite of how it works by default on my T480s. I assumed that the checkbox for "Invert action > Microphone" would do exactly this, but it doesn't seem to work correctly. It does invert the ON/OFF buttons within the actual program, but when I actually press the mic mute button on my keyboard, it goes back to the default state.

**Comment by valinet** [comment]
Hi

Yes, that's the actual functionality, it works as intended. Buttons and checkboxes in the app have effect only in the app and only in regards to the features offered by the program.

As a quick solution for your problem, I'd suggest creating a couple of scripts at OS level that do what you want and use the command line interface of the application to invoke it so that it toggles whatever LED you would like. I don't have much free time at the moment to add any extra major functionality, but I am open to external contributions, that's one of the reasons the code is publicly available here.

**Comment by TonyAki** [comment]
Yep, I've been looking into that. I don't really have any C# experience so I'm not sure I'll be able to contribute to the code, but once I set up a script I'll make sure to post it here!

**Comment by valinet** [comment]
That’s great to hear, awesome. I wish you the best of luck!
